
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsvfdsgfmvhigwditkpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzdmZkc2dmbXZoaWd3ZGl0a3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTY1NDYsImV4cCI6MjA2MTUzMjU0Nn0.I8C-NLAjw7GBHLOoew0-ZHlXOhFEAISJnpoCoL_AzpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
